"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-07-23 00:08:12.284950

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "checkins",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("applications_sent", sa.Integer(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("reflection", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_checkins")),
        sa.UniqueConstraint("date", name=op.f("uq_checkins_date")),
    )
    op.create_table(
        "daily_plans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("raw_input", sa.Text(), nullable=False),
        sa.Column(
            "input_mode",
            sa.Enum("text", "voice", name="input_mode", native_enum=False, length=30),
            nullable=False,
        ),
        sa.Column("rationale", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_daily_plans")),
        sa.UniqueConstraint("date", name=op.f("uq_daily_plans_date")),
    )
    op.create_table(
        "goals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "level",
            sa.Enum("big", "monthly", name="goal_level", native_enum=False, length=30),
            nullable=False,
        ),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("target_date", sa.Date(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("active", "done", "dropped", name="goal_status", native_enum=False, length=30),
            server_default="active",
            nullable=False,
        ),
        sa.Column("target_value", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("unit", sa.String(length=50), nullable=True),
        sa.Column(
            "auto_source",
            sa.Enum(
                "none",
                "applications",
                "tasks_done",
                name="auto_source",
                native_enum=False,
                length=30,
            ),
            server_default="none",
            nullable=False,
        ),
        sa.Column("period_start", sa.Date(), nullable=True),
        sa.Column("period_end", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["goals.id"], name=op.f("fk_goals_parent_id_goals"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_goals")),
    )
    op.create_index(op.f("ix_goals_parent_id"), "goals", ["parent_id"], unique=False)
    op.create_table(
        "job_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job", sa.String(length=50), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column(
            "ran_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_runs")),
        sa.UniqueConstraint("job", "date", name=op.f("uq_job_runs_job")),
    )
    op.create_table(
        "push_subscriptions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("endpoint", sa.Text(), nullable=False),
        sa.Column("p256dh", sa.Text(), nullable=False),
        sa.Column("auth", sa.Text(), nullable=False),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_push_subscriptions")),
        sa.UniqueConstraint("endpoint", name=op.f("uq_push_subscriptions_endpoint")),
    )
    op.create_table(
        "retros",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("week_start", sa.Date(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_retros")),
        sa.UniqueConstraint("week_start", name=op.f("uq_retros_week_start")),
    )
    op.create_table(
        "settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("applications_floor", sa.Integer(), server_default=sa.text("5"), nullable=False),
        sa.Column(
            "read_back_enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "time_blocking_enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("workday_start", sa.Time(), server_default=sa.text("'09:00:00'"), nullable=False),
        sa.Column("workday_end", sa.Time(), server_default=sa.text("'18:00:00'"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_settings")),
    )
    op.create_table(
        "progress_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("goal_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("delta", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "evening_checkin",
                "task",
                "manual",
                name="progress_source",
                native_enum=False,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["goal_id"],
            ["goals.id"],
            name=op.f("fk_progress_log_goal_id_goals"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_progress_log")),
    )
    op.create_index(op.f("ix_progress_log_date"), "progress_log", ["date"], unique=False)
    op.create_index(op.f("ix_progress_log_goal_id"), "progress_log", ["goal_id"], unique=False)
    op.create_table(
        "push_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job", sa.String(length=50), nullable=False),
        sa.Column("subscription_id", sa.Integer(), nullable=False),
        sa.Column(
            "sent_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("status", sa.String(length=200), nullable=False),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["push_subscriptions.id"],
            name=op.f("fk_push_log_subscription_id_push_subscriptions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_push_log")),
    )
    op.create_index(
        op.f("ix_push_log_subscription_id"), "push_log", ["subscription_id"], unique=False
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("plan_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("monthly_goal_id", sa.Integer(), nullable=True),
        sa.Column("done", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("sort", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("gcal_event_id", sa.String(length=200), nullable=True),
        sa.Column("block_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("block_minutes", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["monthly_goal_id"],
            ["goals.id"],
            name=op.f("fk_tasks_monthly_goal_id_goals"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["daily_plans.id"],
            name=op.f("fk_tasks_plan_id_daily_plans"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tasks")),
    )
    op.create_index(op.f("ix_tasks_monthly_goal_id"), "tasks", ["monthly_goal_id"], unique=False)
    op.create_index(op.f("ix_tasks_plan_id"), "tasks", ["plan_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tasks_plan_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_monthly_goal_id"), table_name="tasks")
    op.drop_table("tasks")
    op.drop_index(op.f("ix_push_log_subscription_id"), table_name="push_log")
    op.drop_table("push_log")
    op.drop_index(op.f("ix_progress_log_goal_id"), table_name="progress_log")
    op.drop_index(op.f("ix_progress_log_date"), table_name="progress_log")
    op.drop_table("progress_log")
    op.drop_table("settings")
    op.drop_table("retros")
    op.drop_table("push_subscriptions")
    op.drop_table("job_runs")
    op.drop_index(op.f("ix_goals_parent_id"), table_name="goals")
    op.drop_table("goals")
    op.drop_table("daily_plans")
    op.drop_table("checkins")
    # ### end Alembic commands ###
